### ISSUE TITLE
screensaver setting commands not functional on high sierra

### ISSUE THREAD

**Issue by mtibben** [alichtman/stronghold#15]
https://github.com/alichtman/stronghold/blob/4e0a859c86f82d0634d7432822ef443f5b70bbb4/stronghold.py#L164-L165

These commands are not functional on High Sierra. See https://github.com/drduh/macOS-Security-and-Privacy-Guide/issues/290 for more details

**Comment by alichtman** [comment]
Interesting. I'll look for a workaround. I was wondering if it was just my mac that's been acting up a bit or if my code was buggy.

---

I was reading through https://blog.kolide.com/screensaver-security-on-macos-10-13-is-broken-a385726e2ae2 and saw

> Adding the askForPasswordDelay key to the profile helps to remediate the profile, but only slightly. The actual preference only appears to be synced after the user logs in again.

One potential solution could be to force (or ask nicely for) a restart at the program end. Opinions on that?

**Comment by mtibben** [comment]
Possibly, although there still is no reliable way to query the current settings and know if it _really_ needs to be applied. While hacking on a custom security auditing script, I did have some success using AppleScript to launch the System Preferences, automate clicking on the right things, and reading out the values from the GUI, however this requires the user to give the script Accessibility permissions.

Another approach might be to use osquery which I have just discovered, but haven't dug into that yet

**Comment by alichtman** [comment]
> there still is no reliable way to query the current settings

To some extent, the current settings may not matter. 

1. If they're correctly configured, we overwrite them with the same values and nothing will change (aside from being inefficient.)
2. If they're incorrectly configured, we overwrite them and the behavior will be as expected.

**Comment by alichtman** [comment]
Added this fix in #25. I think this is a good solution, so I'm going to close it for now. Feel free to open this again if you come across a better way to do this.
