### ISSUE TITLE
Possible bug: restart keeps getting interrupted

### ISSUE THREAD

**Issue by VanGTO** [alichtman/stronghold#43]
As above... tried running with both 'stronghold' and 'sudo stronghold' and both have this problem. See what I'm getting below:

```
###########################
# FINAL CONFIGURATION STEPS
###########################

 -> Restart your Mac right now?
[?] This is necessary for some configuration changes to take effect.:  Yes
 >  Yes
    No

Configuration complete after restart!

Restarting in 5 seconds...
4...
3...
2...
1...
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...
WARNING: Configuration not complete! A full restart is necessary.
```

**Comment by alichtman** [comment]
Filing this as a bug. 

Will look into this soon.

**Comment by VanGTO** [comment]
Top man thanks for the update and thanks for the great work.

**Comment by alichtman** [comment]
My pleasure! 

How would you like to see this bug dealt with, assuming that I can't work out the `sudo` issue? I've poured way too many hours into this and (for the moment) am leaning towards the fix I suggested above.

Would that be an acceptable/desired fix, in your opinion?

@VanGTO

**Comment by alichtman** [comment]
Just pushed a fix for this to master. Will go in the next Pypi release once I have time to work out the bug in #42.
